version: "3"

services:

  detector:
    build: ./detector
    container_name: detector
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      LEGIT_TOPIC: streaming.transactions.legit
      FRAUD_TOPIC: streaming.transactions.fraud
      CONN_URL: http://dashboard:5000

networks:
  default:
    external:
      name: kafka-network