version: "3"

services:

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports: 
        - 5000:5000
    environment: 
        PORT: 5000
        FLASK_DEBUG: 1

networks:
  default:
    external:
      name: kafka-network